export let products = [
	{
		name: "Assassin",
		category: "popular game",
		condition: "new",
		rating: 4,
		prize: 500,
		inCart: 0,
	},
	{
		name: "racing",
		category: "popular game",
		condition: "new",
		rating: 5,
		prize: 500,
		inCart: 0,
	},
	{
		name: "Boxer",
		category: "popular game",
		condition: "new",
		rating: 4,
		prize: 500,
		inCart: 0,
	},
	{
		name: "Space War",
		category: "Pre-order game",
		condition: "new",
		prize: 600,
		inCart: 0,
	},
	{
		name: "Cyberpunk",
		category: "Pre-order game",
		condition: "new",
		prize: 600,
		inCart: 0,
	},
	{
		name: "Forge Legends",
		category: "Pre-order game",
		condition: "new",
		prize: 600,
		inCart: 0,
	},
	{
		name: "Super Duper",
		category: "Brand new",
		condition: "new",
		rating: 4,
		prize: 500,
		inCart: 0,
	},
	{
		name: "Black",
		category: "popular game",
		condition: "new",
		rating: 4,
		prize: 500,
		inCart: 0,
	},
	{
		name: "Furious",
		category: "popular game",
		condition: "new",
		rating: 5,
		prize: 500,
		inCart: 0,
	},
	{
		name: "Assassin",
		category: "Pre-used game",
		condition: "used",
		rating: 4,
		prize: 400,
		inCart: 0,
	},
	{
		name: "Furious",
		category: "Pre-used game",
		condition: "used",
		rating: 5,
		prize: 400,
		inCart: 0,
	},
	{
		name: "Boxer",
		category: "Pre-used game",
		condition: "used",
		rating: 4,
		prize: 400,
		inCart: 0,
	},
];
